before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: oyzR9z6NR2sV1OqtQaUFBayLDvFoCW7QU97Uu2WiJ9kInHtpda/c7iFTiY/AikX4oG8vmEcgMXWLBXpmbC07+mYEynVvIOE/LmLPl+uusZZmtCyqRVLaqh/2NIBCrkDsoNx4k1LlR4h9vdURrCbapoNgc6yJpHRxhpF0hIec7xHhLWjcJC5c/rpgDrFhDj5H+4ocgieMAoTgTC5FNWtQ+aFLNtEe06K+x3XzmoeEsfGnF/mayCzgYHrkvIT2jPPCh2a7WwsSAtvLXmjCEZMOgimRqLdF4/Gn0p7jTSwEhGc+4xup3Z9lxB6Fa+6oJsD23G+x/xHGxBDDsygyf3nFvnMPwovVctQ9QXE2cu5NQCtiItwNCfN9Tlzc2p/gNpL4NWpGXZTWEsCTDO3OPghS/QS5TBPl9KWHKAZDGjMAUFKk+3WBuy3jiDshWBEkcvy1W15RiR7QUVF22kodKbnV+WzUQ4FR++X1lF+8aHKeK9K5kYPt0LWh7XF60vVGQiyIVFuonZij8qFNvcRfTimMkDX9TMXM8llH3vHYJscq9SE32ZmGBsgTqpnoxxGV3wRaoChTcDS12iq/1e6Jngnxgf30zXTCNwnGP1BDzEXli4LqsO6k3IHErwNeP6tDMyDF7VFKEQRXzPefVSWAAYzivvSHIAi70b9HfXS7IpTBumY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
